# Generated by Django 5.0.6 on 2024-08-17 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conductores', '0006_remove_conductor_historial_viajes_conductor_history'),
        ('usuarios', '0006_rename_historial_viajes_usuario_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=255)),
                ('destiny', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('cost', models.FloatField()),
                ('dirver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conductores.conductor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
    ]
