# Generated by Django 5.0.4 on 2024-08-09 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('matricula', models.CharField(max_length=10, unique=True)),
                ('capacidad', models.IntegerField()),
                ('marca', models.CharField(max_length=50)),
            ],
        ),
    ]
