# Generated by Django 5.0.6 on 2024-08-10 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conductores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conductor',
            name='calificacion',
        ),
        migrations.RemoveField(
            model_name='conductor',
            name='historial_viajes',
        ),
        migrations.RemoveField(
            model_name='conductor',
            name='vehiculo',
        ),
    ]
